version: "3.7"

services:
  traefik:
    command:
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.network=traefik_proxy"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=${CF_API_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
    container_name: traefik
    environment:
      - "CF_API_EMAIL=${CF_API_EMAIL}"
      - "CF_API_KEY=${CF_API_KEY}"
    image: traefik:v2.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.custom.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.custom.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.custom.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.custom.headers.frameDeny=true"
      - "traefik.http.middlewares.custom.headers.sslredirect=true"
      - "traefik.http.middlewares.custom.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.custom.headers.stsPreload=true"
      - "traefik.http.middlewares.custom.headers.stsSeconds=315360000"
      # Secure Dashboard
      - "traefik.http.middlewares.admin.basicauth.usersfile=/etc/traefik/config/usersfile"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
    networks:
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./config:/etc/traefik/config
      - ./letsencrypt:/etc/traefik/acme
      - ./log:/etc/traefik/log
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    driver: bridge
  traefik_proxy:
    external: true
