version: "3"

services:
  traefik:
    image: traefik:v2.0
    command:
      - --providers.file.filename=/config/dynamic_conf.toml
      - --providers.file.watch=true
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
      - ./letsencrypt:/letsencrypt
