version: "3"

services:
  traefik:
    command:
      - "--api=true"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=${CF_API_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
    container_name: traefik
    environment:
      - "CF_API_EMAIL=${CF_API_EMAIL}"
      - "CF_API_KEY=${CF_API_KEY}"
    image: traefik:v2.0
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/etc/traefik/acme
      - ./log:/etc/traefik/log
      - /var/run/docker.sock:/var/run/docker.sock

  # whoami:
  #   container_name: "simple-service"
  #   image: "containous/whoami"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_NAME}`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
